const SOCKET_EVENTS = {
  CONNECTION: 'connection',
  DISCONNECT: 'disconnect',
  
  JOIN_QUEUE_ROOM: 'joinQueueRoom',
  LEAVE_QUEUE_ROOM: 'leaveQueueRoom',
  
  STUDENT_JOINED_QUEUE: 'studentJoinedQueue',
  STUDENT_LEFT_QUEUE: 'studentLeftQueue',
  
  QUEUE_UPDATE: 'queueUpdate',
  TICKET_UPDATE: 'ticketUpdate',
  TICKET_CALLED: 'ticketCalled',
  TICKET_COMPLETED: 'ticketCompleted',
  TICKET_CANCELLED: 'ticketCancelled',
  
  POSITION_UPDATE: 'positionUpdate',
  WAIT_TIME_UPDATE: 'waitTimeUpdate',
  
  SERVICE_STATUS_UPDATE: 'serviceStatusUpdate',
  SERVICE_OPENED: 'serviceOpened',
  SERVICE_CLOSED: 'serviceClosed',
  SERVICE_PAUSED: 'servicePaused',
  SERVICE_RESUMED: 'serviceResumed',
  
  COUNTER_ASSIGNED: 'counterAssigned',
  COUNTER_FREED: 'counterFreed',
  
  QUEUE_STATISTICS_UPDATE: 'queueStatisticsUpdate',
  SYSTEM_HEALTH_UPDATE: 'systemHealthUpdate',
  
  ERROR: 'error',
  SUCCESS: 'success',
  WARNING: 'warning',
  INFO: 'info',
  
  ADMIN_QUEUE_OVERRIDE: 'adminQueueOverride',
  ADMIN_TICKET_PRIORITY: 'adminTicketPriority',
  ADMIN_SERVICE_CONTROL: 'adminServiceControl',
  
  NOTIFICATION: 'notification',
  ALERT: 'alert',
  ANNOUNCEMENT: 'announcement',
  
  USER_ONLINE: 'userOnline',
  USER_OFFLINE: 'userOffline',
  
  QUEUE_FORECAST_UPDATE: 'queueForecastUpdate',
  PERFORMANCE_METRICS_UPDATE: 'performanceMetricsUpdate'
};

const CLIENT_EVENTS = {
  EMIT: {
    JOIN_QUEUE_ROOM: SOCKET_EVENTS.JOIN_QUEUE_ROOM,
    LEAVE_QUEUE_ROOM: SOCKET_EVENTS.LEAVE_QUEUE_ROOM,
    STUDENT_JOINED_QUEUE: SOCKET_EVENTS.STUDENT_JOINED_QUEUE,
    STUDENT_LEFT_QUEUE: SOCKET_EVENTS.STUDENT_LEFT_QUEUE,
    REQUEST_QUEUE_UPDATE: 'requestQueueUpdate',
    REQUEST_POSITION_UPDATE: 'requestPositionUpdate'
  },
  
  LISTEN: {
    QUEUE_UPDATE: SOCKET_EVENTS.QUEUE_UPDATE,
    TICKET_UPDATE: SOCKET_EVENTS.TICKET_UPDATE,
    TICKET_CALLED: SOCKET_EVENTS.TICKET_CALLED,
    POSITION_UPDATE: SOCKET_EVENTS.POSITION_UPDATE,
    SERVICE_STATUS_UPDATE: SOCKET_EVENTS.SERVICE_STATUS_UPDATE,
    NOTIFICATION: SOCKET_EVENTS.NOTIFICATION,
    ERROR: SOCKET_EVENTS.ERROR
  }
};

const SERVER_EVENTS = {
  EMIT: {
    QUEUE_UPDATE: SOCKET_EVENTS.QUEUE_UPDATE,
    TICKET_UPDATE: SOCKET_EVENTS.TICKET_UPDATE,
    TICKET_CALLED: SOCKET_EVENTS.TICKET_CALLED,
    STUDENT_JOINED_QUEUE: SOCKET_EVENTS.STUDENT_JOINED_QUEUE,
    STUDENT_LEFT_QUEUE: SOCKET_EVENTS.STUDENT_LEFT_QUEUE,
    SERVICE_STATUS_UPDATE: SOCKET_EVENTS.SERVICE_STATUS_UPDATE,
    POSITION_UPDATE: SOCKET_EVENTS.POSITION_UPDATE,
    SYSTEM_HEALTH_UPDATE: SOCKET_EVENTS.SYSTEM_HEALTH_UPDATE,
    NOTIFICATION: SOCKET_EVENTS.NOTIFICATION,
    ERROR: SOCKET_EVENTS.ERROR
  },
  
  LISTEN: {
    JOIN_QUEUE_ROOM: SOCKET_EVENTS.JOIN_QUEUE_ROOM,
    STUDENT_JOINED_QUEUE: SOCKET_EVENTS.STUDENT_JOINED_QUEUE,
    STUDENT_LEFT_QUEUE: SOCKET_EVENTS.STUDENT_LEFT_QUEUE,
    SERVICE_STATUS_UPDATE: SOCKET_EVENTS.SERVICE_STATUS_UPDATE
  }
};

const ROOM_TYPES = {
  QUEUE_ROOM: 'queue-room',
  SERVICE_ROOM: 'service-',
  ADMIN_ROOM: 'admin-room',
  USER_ROOM: 'user-'
};

module.exports = {
  SOCKET_EVENTS,
  CLIENT_EVENTS,
  SERVER_EVENTS,
  ROOM_TYPES
};